---

- name: Generate configuration files
  template: src=access_switch.j2 dest=/home/amurtaza/Pynet/Week5/Exercise2/CFGS/{{item.hostname}}.txt
  with_items: "{{switches}}"
#- name: Generate configuration files
#  template: src=access_switch.j2 dest=/home/amurtaza/Pynet/Week5/Exercise1/CFGS/{{item.hostname}}.txt
#  with_items: "{{ switches }}"
#---
#- name: Generate configuration file
#  template: src=access_switch.j2 dest=/home/amurtaza/Pynet/Week5/Exercise1/CFGS/{{item.hostname}}.txt
#  with_items: test_routers
